# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAiCommit < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/skkdevcraft/git-ai-commit"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.2/git-ai-commit_Darwin_x86_64.tar.gz"
      sha256 "c734b760a0be77227c77030de8e30af449995f187060e99f9204f383d6519547"

      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.2/git-ai-commit_Darwin_arm64.tar.gz"
      sha256 "93bd45cc0d74953fc28a5290d1857b255043867199900be0265b4da1c40e5d04"

      def install
        bin.install "git-ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.2/git-ai-commit_Linux_x86_64.tar.gz"
      sha256 "b637657fc439916e5966f51e95aa8ffd9653e902982ea84eed1c1050d1d1b22d"
      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.2/git-ai-commit_Linux_arm64.tar.gz"
      sha256 "1380c8234bf44bdc2d4dd13cd109cd133bb7b3ae3e37f56ed8981887fea889a0"
      def install
        bin.install "git-ai-commit"
      end
    end
  end
end
