# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAiCommit < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/skkdevcraft/git-ai-commit"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.1/git-ai-commit_Darwin_x86_64.tar.gz"
      sha256 "e9d00b1238b551da7eedacaf96e0ea9dbdba86675a9b97796b62390d64b55b39"

      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.1/git-ai-commit_Darwin_arm64.tar.gz"
      sha256 "ec9d857ebef7864380a54d45a07f99e5127bc6bb9292dda67eaa0a1a764ba66f"

      def install
        bin.install "git-ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.1/git-ai-commit_Linux_x86_64.tar.gz"
      sha256 "7f83f217115245d99b4f2be9b1737eff72415093b0b124840da1f7545f56cc0f"
      def install
        bin.install "git-ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skkdevcraft/git-ai-commit/releases/download/v0.1.1/git-ai-commit_Linux_arm64.tar.gz"
      sha256 "1540a3f1441eaa3caf342ec74f6377e1fa3a4a9166e5fb3282f41a2799f2f9d2"
      def install
        bin.install "git-ai-commit"
      end
    end
  end
end
